### ISSUE TITLE
Dark font on dark background in google-chrome/chromium address bar

### ISSUE THREAD

**Issue by daddy33** [madmaxms/theme-obsidian-2#1]
Hello,

this was introduced with release 2.1.2, the one with the firefox textfields fix (by the way, I can't see the problem in firefox with earlier versions). Can you please check/fix this?

Thanks.

Edit : another issue, also introduced in v2.1.2. On the chromium start/new tab page, the little bar above the thumbnails is white with black fonts, whereas it should be dark with white fonts.

**Comment by madmaxms** [comment]
Hey,
yes, I've seen it. I'm currently working on a light version of the theme while the current one will become the dark-mode. This will fix these kind of issues. When completed, you'll have to enable dark-mode in your theme-settings, Firefox textfields will stay light and the Chrome addressbar will be light text on dark background.
For the moment, I've removed the Firefox workaround, so chrome might look well now...
