### ISSUE TITLE
gtkrc missing color reference

### ISSUE THREAD

**Issue by daddy33** [madmaxms/theme-obsidian-2#10]
Hello,
in the gtk-2.0/gtkrc file, for other colors than blue (regular Obsidian), the

`gtk-color-scheme = "menu_fg: #******"`

line is missing at the beginning, causing an error starting from line 595.
This makes the theme unusable in qt applications (qt5ct error).

Thanks.

**Comment by madmaxms** [comment]
Ok, it's fixed in v2.13. Thanks for reporting!
