### ISSUE TITLE
Wrong color for the cinnamon amber theme

### ISSUE THREAD

**Issue by Dany-Dan** [madmaxms/theme-obsidian-2#13]
Hi,

There is a problem with the amber theme cinnamon.css file.
I think you made a mistake and replaced it with the aqua version.

![cinnamon-amber](https://user-images.githubusercontent.com/59367957/152176749-0d449102-b248-4894-817c-86d1a42e868b.png)

I also take this opportunity to point out another small error in the gtk.css files (gtk-3.20 only) of all themes.
The .csd.popup decoration class is duplicated at lines 7360 and 8598.

Thank you very much for this great theme and keep up the good work !

**Comment by madmaxms** [comment]
Fixed. Thanks for reporting! (Release 2.22)
