### ISSUE TITLE
Gnome 43 compatibility

### ISSUE THREAD

**Issue by alexd73** [madmaxms/theme-obsidian-2#15]
I love your theme. And I like use new updates.
In Gnome 43, this theme was partially applied. System's windows still displayd Adwita theme.
![image](https://user-images.githubusercontent.com/1692056/193403083-5339ea1a-4409-4d23-8027-8c2ebc17f0fe.png)

Do you have a plan to fix this?

**Comment by alexd73** [comment]
I noticed an incorrect corner if the shell is Obsidian 2
![image](https://user-images.githubusercontent.com/1692056/193404747-cfbb53c6-c6ba-4422-8b48-37ed3c9e1f37.png)

**Comment by madmaxms** [comment]
And finally, here it is. (Release 2.22)
