### ISSUE TITLE
White dialogs on Firefox 59.0.2

### ISSUE THREAD

**Issue by dallasrevolt** [madmaxms/theme-obsidian-2#4]
Dialogs don't match the dark color of the theme.
Ubuntu 18.04 with Gnome 3.28.1

![screenshot from 2018-05-02 19-08-02](https://user-images.githubusercontent.com/31676836/39555160-983353f8-4e3c-11e8-8de6-aba1e7ba9aa2.png)

**Comment by madmaxms** [comment]
fixed
