### ISSUE TITLE
Cinnamon theme notification: cinnamon.css missing semi-colon

### ISSUE THREAD

**Issue by daddy33** [madmaxms/theme-obsidian-2#9]
Hello,
notification display is corrupted in Cinnamon. The cause seems just to be a semi-colon missing in cinnamon.css on line 896:

background-color: rgba(47, 53, 53, 0.9)
-->background-color: rgba(47, 53, 53, 0.9);

Regards.

**Comment by madmaxms** [comment]
should be fixed now, thanks for reporting!
